import { TimePreset } from '../types/chess';

export const TIME_PRESETS: TimePreset[] = [
  // Bullet
  {
    id: 'bullet_1_0',
    nameBn: '1 min (Bullet)',
    nameEn: '1 min (Bullet)',
    category: 'bullet',
    baseMinutes: 1,
    incrementSeconds: 0,
    mode: 'sudden_death',
  },
  {
    id: 'bullet_1_1',
    nameBn: '1 min + 1s (Bullet)',
    nameEn: '1 min + 1s (Bullet)',
    category: 'bullet',
    baseMinutes: 1,
    incrementSeconds: 1,
    mode: 'fischer',
  },
  {
    id: 'bullet_2_1',
    nameBn: '2 min + 1s (Bullet)',
    nameEn: '2 min + 1s (Bullet)',
    category: 'bullet',
    baseMinutes: 2,
    incrementSeconds: 1,
    mode: 'fischer',
  },

  // Blitz
  {
    id: 'blitz_3_0',
    nameBn: '3 min (Blitz)',
    nameEn: '3 min (Blitz)',
    category: 'blitz',
    baseMinutes: 3,
    incrementSeconds: 0,
    mode: 'sudden_death',
  },
  {
    id: 'blitz_3_2',
    nameBn: '3 min + 2s (Blitz)',
    nameEn: '3 min + 2s (Blitz)',
    category: 'blitz',
    baseMinutes: 3,
    incrementSeconds: 2,
    mode: 'fischer',
  },
  {
    id: 'blitz_5_0',
    nameBn: '5 min (Blitz)',
    nameEn: '5 min (Blitz)',
    category: 'blitz',
    baseMinutes: 5,
    incrementSeconds: 0,
    mode: 'sudden_death',
  },
  {
    id: 'blitz_5_3',
    nameBn: '5 min + 3s (Blitz)',
    nameEn: '5 min + 3s (Blitz)',
    category: 'blitz',
    baseMinutes: 5,
    incrementSeconds: 3,
    mode: 'fischer',
  },
  {
    id: 'blitz_5_5',
    nameBn: '5 min + 5s (Blitz)',
    nameEn: '5 min + 5s (Blitz)',
    category: 'blitz',
    baseMinutes: 5,
    incrementSeconds: 5,
    mode: 'fischer',
  },

  // Rapid
  {
    id: 'rapid_10_0',
    nameBn: '10 min (Rapid)',
    nameEn: '10 min (Rapid)',
    category: 'rapid',
    baseMinutes: 10,
    incrementSeconds: 0,
    mode: 'sudden_death',
  },
  {
    id: 'rapid_15_10',
    nameBn: '15 min + 10s (Rapid)',
    nameEn: '15 min + 10s (Rapid)',
    category: 'rapid',
    baseMinutes: 15,
    incrementSeconds: 10,
    mode: 'fischer',
  },
  {
    id: 'rapid_20_0',
    nameBn: '20 min (Rapid)',
    nameEn: '20 min (Rapid)',
    category: 'rapid',
    baseMinutes: 20,
    incrementSeconds: 0,
    mode: 'sudden_death',
  },

  // Classical
  {
    id: 'classical_30_0',
    nameBn: '30 min (Classical)',
    nameEn: '30 min (Classical)',
    category: 'classical',
    baseMinutes: 30,
    incrementSeconds: 0,
    mode: 'sudden_death',
  },
  {
    id: 'classical_60_0',
    nameBn: '60 min (Classical)',
    nameEn: '60 min (Classical)',
    category: 'classical',
    baseMinutes: 60,
    incrementSeconds: 0,
    mode: 'sudden_death',
  },
  {
    id: 'classical_90_30',
    nameBn: '90 min + 30s (FIDE)',
    nameEn: '90 min + 30s (FIDE)',
    category: 'classical',
    baseMinutes: 90,
    incrementSeconds: 30,
    mode: 'fischer',
  },
];
